name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn eslint
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: e2e test
        uses: cypress-io/github-action@v2
        with:
          command: yarn test:e2e
          start: yarn start-prod
          wait-on: http://localhost:5000
      - name: deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pokedex-0402"
          heroku_email: "copppe@gmail.com"
          healthcheck: "https://pokedex-0402.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
